dist: trusty
sudo: required
language: node_js
node_js:
  - '8'
os:
  - linux
addons:
  chrome: stable
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=chromium-browser
install:
  - npm install
before_script:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
script:
  - npm run lint
  - npm run test:once
  - npm run build:lib
  - npm run build:demo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist/apps/demo-packaged
  on:
    branch: master
